### ISSUE TITLE
BHoM_UI: Does not load in Dynamo

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_UI#86]
hi,

I spent some time with @FraserGreenroyd and @ZiolkowskiJakub  but we could not find solution. Problem is when I build Dynamo it copies all files from  `Assembly folder` to `Bin `subfolder but I do not have any files in main BHoM folder therefore Dynamo Package does not load . I appreciate any help and advice. 

![image](https://user-images.githubusercontent.com/26113670/56674266-a2516a80-66b1-11e9-88f1-3f78e86f08b1.png)

![image](https://user-images.githubusercontent.com/26113670/56674218-86e65f80-66b1-11e9-810a-c9f94f8e0ece.png)

**Comment by al-fisher** [comment]
Can anyone else recreate this bug - and provide details too? Thanks

**Comment by adecler** [comment]
I've just updated my code and it works for me.

**Comment by michaldengusiak** [comment]
I deleted my Dynamo repo and cloned again unfortunately no difference... still does not work ...hmm

**Comment by epignatelli** [comment]
@michaldengusiak is this still an issue? 
If so, is it an issue if you use: A. CodeAssistant, B. Installer, C. Compile from source?

**Comment by michaldengusiak** [comment]
ok I still have wrong folder structure but now works, I delete all report and rebuild one by one and found problematic that I deleted ...
